import type { CoinPriceData } from '../types';

export const FALLBACK_MARQUEE_TICKERS: CoinPriceData[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    image: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    formattedCurrentPrice: '$67,420.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '-1.20%',
    priceChangeFiat: '-$809.04',
    isPriceChangePositive: false,
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    image: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    formattedCurrentPrice: '$3,450.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+2.40%',
    priceChangeFiat: '+$82.80',
    isPriceChangePositive: true,
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    image: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
    formattedCurrentPrice: '$145.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+5.10%',
    priceChangeFiat: '+$7.40',
    isPriceChangePositive: true,
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    image: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
    formattedCurrentPrice: '$580.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+0.30%',
    priceChangeFiat: '+$1.74',
    isPriceChangePositive: true,
  },
  {
    symbol: 'USDT',
    name: 'Tether',
    image: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    formattedCurrentPrice: '$1.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+0.01%',
    priceChangeFiat: '+$0.00',
    isPriceChangePositive: true,
  },
];
