import type { CoinPriceData } from '../types';

export const MARQUEE_BENCHMARK_SYMBOLS = [
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'USDT',
] as const;

export const FALLBACK_MARQUEE_TICKERS: CoinPriceData[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    image: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    currentPrice: 67_420,
    marketCap: 0,
    priceChange24h: -1.2,
    currency: 'usd',
    source: 'fallback',
    formattedCurrentPrice: '$67,420.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '-1.20%',
    priceChangeFiat: '-$809.04',
    isPriceChangePositive: false,
    hasValidPrice: true,
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    image: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    currentPrice: 3_450,
    marketCap: 0,
    priceChange24h: 2.4,
    currency: 'usd',
    source: 'fallback',
    formattedCurrentPrice: '$3,450.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+2.40%',
    priceChangeFiat: '+$82.80',
    isPriceChangePositive: true,
    hasValidPrice: true,
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    image: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
    currentPrice: 145,
    marketCap: 0,
    priceChange24h: 5.1,
    currency: 'usd',
    source: 'fallback',
    formattedCurrentPrice: '$145.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+5.10%',
    priceChangeFiat: '+$7.40',
    isPriceChangePositive: true,
    hasValidPrice: true,
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    image: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
    currentPrice: 580,
    marketCap: 0,
    priceChange24h: 0.3,
    currency: 'usd',
    source: 'fallback',
    formattedCurrentPrice: '$580.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+0.30%',
    priceChangeFiat: '+$1.74',
    isPriceChangePositive: true,
    hasValidPrice: true,
  },
  {
    symbol: 'USDT',
    name: 'Tether',
    image: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    currentPrice: 1.0,
    marketCap: 0,
    priceChange24h: 0.01,
    currency: 'usd',
    source: 'fallback',
    formattedCurrentPrice: '$1.00',
    formattedMarketCap: '$0.00',
    priceChangePercent: '+0.01%',
    priceChangeFiat: '+$0.00',
    isPriceChangePositive: true,
    hasValidPrice: true,
  },
];
