// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Production: set DATABASE_URL=file:/data/prod.db (persistent volume mount).
    // Development: DATABASE_URL=file:./dev.db (see .env.example).
    url: process.env["DATABASE_URL"],
  },
});
