// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Production: Neon pooled connection string (see .env.example).
    // Development: local or Neon dev-branch PostgreSQL URL.
    url: process.env["DATABASE_URL"],
  },
});
